---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: verify-signed-rpms
spec:
  params:
    - name: IMAGE
      type: string
      description: The image to use for this task
      default: ""
    - name: INPUT
      type: string
      description: "AppStudio snapshot or a reference to a container image"
    - name: FAIL_UNSIGNED
      type: string
      description: "[true | false] If true fail if unsigned RPMs were found"
      default: ""
  results:
    - name: verification-output
      description: "The output of the rpm verification"
  steps:
    - name: verify-signed-rpms
      image: "$(params.IMAGE)"
      script: |
        #!/bin/bash
        set -ex

        rpm_verifier \
          --input "$(params.INPUT)" \
          --fail-unsigned "$(params.FAIL_UNSIGNED)" \
          --workdir "$(workspaces.results-temp.path)" | tee $(results.verification-output.path)
  workspaces:
    - description: The folder where we write the results
      mountPath: /results
      name: results-temp
